Este notebook esta destinado a corroborar que los datos que vamos a utilizar para nuestro dashboard estén limpios.

In [1]:
import pandas as pd

In [4]:
youtube_trends = pd.read_csv("datasets/trending_by_time.csv")

In [5]:
youtube_trends.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12343 entries, 0 to 12342
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   record_id       12343 non-null  int64
 1   region          12343 non-null  object
 2   trending_date   12343 non-null  object
 3   category_title  12343 non-null  object
 4   videos_count    12343 non-null  int64
dtypes: int64(2), object(3)
memory usage: 482.3+ KB

In [6]:
youtube_trends.head()

,record_id,region,trending_date,category_title,videos_count
0,1,France,2017-11-14 00:00:00.000000,Autos & Vehicles,8
1,2,France,2017-11-15 00:00:00.000000,Autos & Vehicles,2
2,3,France,2017-11-16 00:00:00.000000,Autos & Vehicles,6
3,4,France,2017-11-17 00:00:00.000000,Autos & Vehicles,8
4,5,France,2017-11-18 00:00:00.000000,Autos & Vehicles,4

In [8]:
youtube_trends.tail()

,record_id,region,trending_date,category_title,videos_count
12338,12339,United States,2018-06-10 00:00:00.000000,Travel & Events,2
12339,12340,United States,2018-06-11 00:00:00.000000,Travel & Events,2
12340,12341,United States,2018-06-12 00:00:00.000000,Travel & Events,2
12341,12342,United States,2018-06-13 00:00:00.000000,Travel & Events,2
12342,12343,United States,2018-06-14 00:00:00.000000,Travel & Events,2

In [9]:
youtube_trends.duplicated().sum()

np.int64(0)

El dataset ya se encuentra limpio y libre de duplicados, limpiar la columna `trending_date` dejando unicamente la fecha

In [17]:
youtube_trends["trending_date"] = pd.to_datetime(youtube_trends["trending_date"]).dt.date

In [18]:
youtube_trends.head()

   record_id  region trending_date    category_title  videos_count
0          1  France    2017-11-14  Autos & Vehicles             8
1          2  France    2017-11-15  Autos & Vehicles             2
2          3  France    2017-11-16  Autos & Vehicles             6
3          4  France    2017-11-17  Autos & Vehicles             8
4          5  France    2017-11-18  Autos & Vehicles             4

Con esto nuestros datos están listos para trabajar en Tableau

In [ ]:
youtube_trends.to_csv("trending_by_time_clean.csv", index=False)